Repository ucsb-cs156-f22/f22-5pm-happycows, pull requests merged in 2022-12, with the labels that each got.

#49 cw - added cowHealth field to UserCommons.java
  frontend/src/main/components/Commons/FarmStats.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: 10, f22-5pm-4

#68 cw - frontend changes to launch cow health updates
  frontend/src/fixtures/jobsFixtures.js
  frontend/src/main/components/Jobs/UpdateCowHealthForm.js
  frontend/src/main/pages/AdminJobsPage.js
  frontend/src/stories/components/Jobs/UpdateCowHealthForm.stories.mdx
  frontend/src/stories/pages/AdminJobsPage.stories.js
  frontend/src/tests/components/Jobs/UpdateCowHealthForm.test.js
  frontend/src/tests/pages/AdminJobsPage.test.js
Labels: 10, f22-5pm-4

#64 Harvard - implemented carrying capacity in frontend create and update
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
Labels: 10, f22-5pm-3

#73 pc - refactor UpdateCowHealth job and tests and add more debugging ou…
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJob.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobFactory.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobFactoryTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobTests.java
Labels: Staff PR

#76 Add cow health to leaderboard, and fix bug with job logging (crashes when more than 255 chars)
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
  src/main/java/edu/ucsb/cs156/happiercows/entities/jobs/Job.java
Labels: Staff PR

#71 cw - Adjust cow health over time
  frontend/src/fixtures/jobsFixtures.js
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/jobs/Job.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJob.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobFactory.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/JobsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobFactoryTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobTests.java
Labels: f22-5pm-4
