Repository ucsb-cs156-f22/f22-5pm-happycows, pull requests merged in 2022-11, with the labels that each got.

#9 AK - add sourceRepo to systeminfo
  src/main/java/edu/ucsb/cs156/happiercows/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/happiercows/services/SystemInfoServiceImpl.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/happiercows/controllers/SystemInfoControllerTests.java
Labels: 10, f22-5pm-3

#6 ol - added placeholder job to milk cows on backend
  src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
Labels: f22-5pm-4

#8 Modified Footer Github Link to Link from System Info Source Repo
  frontend/src/fixtures/systemInfoFixtures.js
  frontend/src/main/components/Nav/Footer.js
  frontend/src/main/layouts/BasicLayout/BasicLayout.js
  frontend/src/stories/layouts/BasicLayout/Footer.stories.js
  frontend/src/tests/components/Nav/Footer.test.js
Labels: f22-5pm-3

#15 cw - Add placeholder for jobs to update cow health and produce "instructor report"
  src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
Labels: f22-5pm-4

#14 cs - removed .DS_Store and added it to .gitignore
  .DS_Store
  .gitignore
Labels: 5, f22-5pm-3

#13 added SystemInfoServiceImplTest for sourceRepo
  src/main/resources/application-development.properties
  src/test/java/edu/ucsb/cs156/happiercows/services/SystemInfoServiceImplTests.java
Labels: 5, f22-5pm-3

#21 bb - Adding path filters to workflows so frontend/backend tests only trigger when the frontend/backend respectively changes
  .github/workflows/10-backend-unit.yml
  .github/workflows/12-backend-jacoco.yml
  .github/workflows/14-backend-pitest.yml
  .github/workflows/30-frontend-tests.yml
  .github/workflows/32-frontend-coverage.yml
  .github/workflows/34-frontend-mutation-testing.yml
  .github/workflows/36-frontend-eslint.yml
Labels: f22-5pm-4

#7 ar - added jobMilkCows place holder for admin jobs
  frontend/src/main/components/Jobs/MilkCowsJobForm.js
  frontend/src/main/pages/AdminJobsPage.js
Labels: f22-5pm-4

#33 bb - Adding column called username to leaderboard that maps user id to the correct username
  frontend/src/fixtures/leaderboardFixtures.js
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: f22-5pm-4, STAFF: ready for review

#35 Harvard fix cow bought bug
  src/main/java/edu/ucsb/cs156/happiercows/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/errors/NoCowsException.java
  src/main/java/edu/ucsb/cs156/happiercows/errors/NotEnoughMoneyException.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: f22-5pm-3

#16 fixed timezone issue
  frontend/src/fixtures/jobsFixtures.js
  frontend/src/tests/components/Jobs/JobsTable.test.js
  frontend/src/tests/pages/AdminJobsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/HappierCowsApplication.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/jobs/Job.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/JobsControllerTests.java
Labels: 10, f22-5pm-3

#32 ar - added instructorReport and updateCowHealth job placeholders
  frontend/src/main/components/Jobs/InstructorReportForm.js
  frontend/src/main/components/Jobs/UpdateCowHealthForm.js
  frontend/src/main/pages/AdminJobsPage.js
Labels: f22-5pm-4, STAFF: ready for review

#40 38 AK add tests to make the stryker mutation and jest coverage 100
  frontend/src/fixtures/systemInfoFixtures.js
  frontend/src/main/components/Jobs/JobComingSoon.js
  frontend/src/stories/components/Nav/AppNavbar.stories.js
  frontend/src/stories/layouts/BasicLayout/Footer.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/Nav/Footer.test.js
  frontend/src/tests/utils/systemInfo.test.js
Labels: f22-5pm-3

#42 ak - adding pc's changes from 6pm happycows
  frontend/src/fixtures/commonsPlusFixtures.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/utils/commonsUtils.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminListCommonsPage.test.js
  frontend/src/tests/utils/commonsUtil.test.js
Labels: 10, f22-5pm-3, MERGE when CI/CD ✅

#58 bb - Creating and implementing CowDeath entity and repository
  src/main/java/edu/ucsb/cs156/happiercows/entities/CowDeath.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CowDeathRepository.java
Labels: 10, f22-5pm-4

#36 lg - change background visibility
  frontend/src/main/components/OurTable.js
  frontend/src/main/pages/LeaderboardPage.js
Labels: 10, f22-5pm-4

#46 cs - join commons column
  frontend/src/main/pages/HomePage.js
  frontend/src/tests/components/Commons/CommonsList.test.js
  frontend/src/tests/pages/HomePage.test.js
Labels: 10, f22-5pm-3

#48 cw - REMOVE the "This game will end on" component
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/fixtures/userCommonsFixtures.js
  frontend/src/main/components/Commons/CommonsOverview.js
  frontend/src/tests/pages/LeaderboardPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: 10, f22-5pm-4
